const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const manifestPath = path.join(root, 'tools', 'source-scripts.json');
const outputPath = path.join(root, 'src', 'game.bundle.js');

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, 'utf8'));
}

function assertSafeSource(relativePath) {
  if (!relativePath || path.isAbsolute(relativePath)) {
    throw new Error(`Invalid source path: ${relativePath}`);
  }
  const normalized = relativePath.replace(/\\/g, '/');
  if (!normalized.startsWith('src/') || normalized.includes('..')) {
    throw new Error(`Source must stay inside src/: ${relativePath}`);
  }
  if (normalized === 'src/game.bundle.js') {
    throw new Error('The generated bundle cannot be used as a source.');
  }
  return normalized;
}

function build() {
  const sources = readJson(manifestPath).map(assertSafeSource);
  const seen = new Set();
  const chunks = [];

  for (const source of sources) {
    if (seen.has(source)) throw new Error(`Duplicate source in manifest: ${source}`);
    seen.add(source);

    const absolute = path.join(root, source);
    if (!fs.existsSync(absolute)) throw new Error(`Missing source file: ${source}`);
    const code = fs.readFileSync(absolute, 'utf8');
    chunks.push(`\n/* ===== ${source} ===== */\n${code}\n`);
  }

  const banner = [
    '/*',
    ' * Streets of Russia single-file browser build.',
    ' * Generated by tools/build-single.js.',
    ' * Edit source files and rerun npm run build or node tools/build-single.js.',
    ' */',
    ''
  ].join('\n');

  fs.writeFileSync(outputPath, banner + chunks.join('\n'), 'utf8');
  console.log(`Built ${path.relative(root, outputPath)} from ${sources.length} source files.`);
}

build();
