window.Assets = {
  backgrounds:{
    main:'assets/backgrounds/Main.png',
    level1:['assets/backgrounds/street01.png','assets/backgrounds/street02.png','assets/backgrounds/street03.png']
  },
  audio:{
    music:{
      menuTheme:'assets/audio/music/menu-theme.mp3',
      levelTheme:'assets/audio/music/level-theme.mp3',
      street01Theme:'assets/audio/music/street01-theme.mp3',
      street02Theme:'assets/audio/music/street02-theme.mp3',
      street03Theme:'assets/audio/music/street03-theme.mp3',
      bossTheme:'assets/audio/music/boss-theme.mp3'
    },
    sfx:{
      menuMove:'assets/audio/sfx/menu-move.wav',
      menuSelect:'assets/audio/sfx/menu-select.wav',
      punch:'assets/audio/sfx/punch.wav',
      punch1:'assets/audio/sfx/punch1.mp3',
      punch2:'assets/audio/sfx/punch2.mp3',
      punch3:'assets/audio/sfx/punch3.mp3',
      hit:'assets/audio/sfx/hit.wav',
      enemyDown:'assets/audio/sfx/enemy-down.wav',
      playerDown:'assets/audio/sfx/player-down.wav',
      waveStart:'assets/audio/sfx/wave-start.wav',
      waveClear:'assets/audio/sfx/wave-clear.wav',
      bossAppear:'assets/audio/sfx/boss-appear.wav'
    }
  },
  boris:{
    idle:'assets/characters/boris/Idle.png',
    walk:['assets/characters/boris/walk0.png','assets/characters/boris/walk1.png','assets/characters/boris/walk2.png'],
    punch:['assets/characters/boris/punch0.png','assets/characters/boris/punch1.png','assets/characters/boris/punch2.png'],
    knockdown:'assets/characters/boris/knockdown.png'
  },
  alexey:{
    idle:'assets/characters/alex/Idle.png',
    walk:['assets/characters/alex/walk0.png','assets/characters/alex/walk1.png','assets/characters/alex/walk2.png'],
    punch:['assets/characters/alex/punch0.png','assets/characters/alex/punch1.png','assets/characters/alex/punch2.png'],
    knockdown:'assets/characters/alex/knockdown.png'
  },
  anna:{
    idle:'assets/characters/anna/idle.png',
    walk:['assets/characters/anna/walk0.png','assets/characters/anna/walk1.png','assets/characters/anna/walk2.png'],
    punch:['assets/characters/anna/punch0.png','assets/characters/anna/punch1.png','assets/characters/anna/punch2.png'],
    knockdown:'assets/characters/anna/knockdown.png'
  },
  dog:{
    idle:'assets/enemies/dog-regime/idle.png',
    walk:['assets/enemies/dog-regime/walk0.png','assets/enemies/dog-regime/walk1.png'],
    attack:['assets/enemies/dog-regime/punch0.png','assets/enemies/dog-regime/punch1.png'],
    dead:'assets/enemies/dog-regime/dead.png'
  },
  sucker:{
    idle:'assets/enemies/sucker/idle.png',
    walk:['assets/enemies/sucker/walk0.png','assets/enemies/sucker/walk1.png'],
    attack:['assets/enemies/sucker/punch0.png','assets/enemies/sucker/punch1.png'],
    slide:'assets/enemies/sucker/slideAttack0.png',
    bite:['assets/enemies/sucker/bite0.png','assets/enemies/sucker/bite1.png'],
    dead:'assets/enemies/sucker/dead.png'
  },
  bastard:{
    idle:'assets/enemies/bastard/idle.png',
    fall:'assets/enemies/bastard/fall.png',
    walk:['assets/enemies/bastard/walk0.png','assets/enemies/bastard/walk1.png','assets/enemies/bastard/walk2.png']
  }
};
